var views = {
		v1  : {name : 'view1' ,desc:'Donut2D Default Fill',  fnName: 'createDonut2DFillDefault',    		file : 'donut2d-fill-default.js'},
		v2  : {name : 'view2' ,desc:'Donut2D Slice Fill',  fnName: 'createDonut2DFillSliceDefault',      	file : 'donut2d-fill-default-onlyslice.js'},
		v3  : {name : 'view3' ,desc:'Donut2D Default Fill',  fnName: 'createDonut2DFillRadial',    			file : 'donut2d-fill-radial.js'},
		v4  : {name : 'view4' ,desc:'Donut2D Radial Fill',  fnName: 'createDonut2DFillSliceRadial',     	file : 'donut2d-fill-radial-onlyslice.js'},
		v5  : {name : 'view5' ,desc:'Donut2D Listenner',  fnName: 'createDonut2DListener',     			file : 'donut2d-listener.js'},
		v6  : {name : 'view6' ,desc:'Donut2D Stroke',  fnName: 'createDonut2DDraw',     	 			file : 'donut2d-draw.js'},
		v7  : {name : 'view7' ,desc:'Donut2D Slice Stroke',  fnName: 'createDonut2DDrawSlice', 	  	 		file : 'donut2d-draw-onlyslice.js'},
		v8  : {name : 'view8' ,desc:'Donut2D Divergence',  fnName: 'createDonut2DDivergence', 	 		file : 'donut2d-divergence.js'},
		v9  : {name : 'view9' ,desc:'Donut2D Radial Label',  fnName: 'createDonut2DLabelRadial',   	 		file : 'donut2d-label-radial.js'},
		v10 : {name : 'view10' ,desc:'Donut2D Border Label', fnName: 'createDonut2DLabelBorder', 	 		file : 'donut2d-label-border.js'},
		v11 : {name : 'view11' ,desc:'Donut2D Linear Effect', fnName: 'createDonut2DEffectLinear', 	 		file : 'donut2d-effect-linear.js'},
		v12 : {name : 'view12' ,desc:'Donut2D Reflection Effect', fnName: 'createDonut2DEffectReflection', 		file : 'donut2d-effect-reflection.js'},
		v13 : {name : 'view13' ,desc:'Donut2D Compound Effect', fnName: 'createDonut2DEffectCompound', 		file : 'donut2d-effect-multiple.js'},
		v14 : {name : 'view14' ,desc:'Donut2D Animation Alpha', fnName: 'createDonut2DAnimationAlpha', 		file : 'donut2d-animation-alpha.js'},
		v15 : {name : 'view15' ,desc:'Donut2D Slice Animation Divergence', fnName: 'createDonut2DAnimationDivergence', 	file : 'donut2d-animation-divergence.js'},
		v16 : {name : 'view16' ,desc:'Donut2D Animation Label', fnName: 'createDonut2DAnimationLabel', 		file : 'donut2d-animation-label.js'},
};
